package io.devholic.restflux.core.response


enum class Header(val value: String) {
    AccessControlAllowOrigin("Access-Control-Allow-Origin"),
    AcceptPatch("Accept-Patch"),
    AcceptRanges("Accept-Ranges"),
    Age("Age"),
    Allow("Allow"),
    AltSvc("Alt-Svc"),
    CacheControl("Cache-Control"),
    Connection("Connection"),
    ContentDisposition("Content-Disposition"),
    ContentEncoding("Content-Encoding"),
    ContentLanguage("Content-Language"),
    ContentLength("Content-Length"),
    ContentLocation("Content-Location"),
    ContentMD5("Content-MD5"),
    ContentRange("Content-Range"),
    ContentType("Content-Type"),
    Date("Date"),
    ETag("ETag"),
    Expires("Expires"),
    LastModified("Last-Modified"),
    Link("Link"),
    Location("Location"),
    P3P("P3P"),
    Pragma("Pragma"),
    ProxyAuthenticate("Proxy-Authenticate"),
    PublicKeyPins("Public-Key-Pins"),
    Refresh("Refresh"),
    RetryAfter("Retry-After"),
    Server("Server"),
    SetCookie("Set-Cookie"),
    StrictTransportSecurity("Strict-Transport-Security"),
    Trailer("Trailer"),
    TransferEncoding("Transfer-Encoding"),
    TSV("TSV"),
    Upgrade("Upgrade"),
    Vary("Vary"),
    Via("Via"),
    Warning("Warning"),
    WWWAuthenticate("WWW-Authenticate"),
    XFrameOptions("X-Frame-Options"),
    XPoweredBy("X-Powered-By")
}
